modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/Afroduckie/AGBulkMinerReleases/issues" #optional
[[mods]] #mandatory
modId="agbulkminer" #mandatory
version="${file.jarVersion}" #mandatory
displayName="[AG] Strip-Miner's Toolchest" #mandatory
updateJSONURL="https://github.com/Afroduckie/AGBulkMinerReleases/blob/main/update.json" #optional
displayURL="https://github.com/Afroduckie/AGBulkMinerReleases/releases" #optional
logoFile="agbulkminer_banner.png" #optional
credits="Credit goes to William of AndrielGaming." #optional
authors="AndrielGaming William. Special thanks to Daniel!" #optional
description='''
Adds a variety of vanilla-friendly tools meant to help with menial tasks.
Currently features the Hammer, for bulk-mining, and the Dredge, for bulk digging.

Will later implement a tree-capitating axe and a bulk-farming scythe as well as 2 power tools.

'''
